{{- if .Values.localRegistryHosting.enabled }}
{{- $clusterHost := printf "%s.%s" .Values.service.name .Release.Namespace }}
{{- $clusterAddr := printf "%s:%d" $clusterHost (.Values.service.port | int) }}
{{- $nodeAddr := printf "%s:%d" $clusterHost (.Values.service.nodePort | default .Values.service.port | int) }}
{{- $externalAddr := .Values.localRegistryHosting.externalAddr | required "service.externalAddr required for local registry hosting" }}
{{- $data := dict "host" $externalAddr "hostFromContainerRuntime" $nodeAddr "hostFromClusterNetwork" $clusterAddr }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  localRegistryHosting.v1: |
  {{- $data | toYaml | nindent 4 }}
{{- end }}
